project:
  type: website

website:
  title: "Lukas Warode"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Projects & Publications
        href: work.qmd
#      - text: Blog
#        href: blog.qmd
      - icon: fas fa-adjust
        id: theme-toggle

format:
  html:
    theme:
      light: lux
      # dark: darkly
    css: styles.css
    toc: true
    toc-depth: 2

editor: visual

